name=input("Enter your name: ")
print(f"Hi, welcome {name}")
num1=int(input("Enter your first number: "))
num2=int(input("Enter your second number: "))
print(f"{num1} + {num2} = {num1+num2}")
print(f"The difference of {num1} and {num2} is {num1-num2}")
print(f"The product of {num1} and {num2} is {num1*num2}")
print(f"the quotient of {num1} and {num2} is {num1/num2}")
print(f"The remainder of {num1} and {num2} is {num1/num2}")
print(f"The sum of {num1} and {num2} is {num1+num2}")